#!/bin/bash
#
#
#(The MIT License)
#
#Copyright (C) 2016 Leonardo Esparis <leo.leo.leoxnidas.c.14@gmail.com>.
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.


PUBLIC_IP="$(dig +short myip.opendns.com @resolver1.opendns.com)"


help() {
	echo -e "Creator: Leonardo Esparis"
	echo -e "Email: leo.leo.leoxnidas.c.14@gmail.com"
	echo -e "License: MIT\n"
	echo -e "App help:"
	echo -e "\twhatismyip [options]"
	echo -e "\nDescription:"
	echo -e "\tThis tool allow you to get your current public ip address"
	echo -e "\nOptions:"
	echo -e "\t-q\t quiet mode"
	echo -e "\t-m\t custom user message"
	echo -e "\t-h\t help text"
}

case "$1" in

	"-q")
	echo "$PUBLIC_IP"
	;;

	"-m")
	if [[ "$2" == "" ]]
		then
		echo "$PUBLIC_IP"
	else
		echo "$2 $PUBLIC_IP"
	fi
	;;

	"")
	echo "$(hostname), this is your public ip address: $PUBLIC_IP"
	;;
	
	*|"-h")
	help
	;;

esac

